export const pokemonColumns = [
  {
    name: 'ID',
    key: 'id',
    width: 60,
  },
  {
    name: 'Name',
    key: 'name',
  },
  {
    name: 'Type',
    key: 'type',
  },
];
export const pokemonItems = [
  {
    id: 1,
    name: 'Bulbasaur',
    type: ['Grass', 'Poison'],
    health: 45,
    attack: 49,
    defense: 49,
  },
  {
    id: 2,
    name: 'Ivysaur',
    type: ['Grass', 'Poison'],
    health: 60,
    attack: 62,
    defense: 63,
  },
  {
    id: 3,
    name: 'Venusaur',
    type: ['Grass', 'Poison'],
    health: 80,
    attack: 82,
    defense: 83,
  },
  {
    id: 4,
    name: 'Charmander',
    type: ['Fire'],
    health: 39,
    attack: 52,
    defense: 43,
  },
  {
    id: 5,
    name: 'Charmeleon',
    type: ['Fire'],
    health: 58,
    attack: 64,
    defense: 58,
  },
  {
    id: 6,
    name: 'Charizard',
    type: ['Fire', 'Flying'],
    health: 78,
    attack: 84,
    defense: 78,
  },
  {
    id: 7,
    name: 'Squirtle',
    type: ['Water'],
    health: 44,
    attack: 48,
    defense: 65,
  },
  {
    id: 8,
    name: 'Wartortle',
    type: ['Water'],
    health: 59,
    attack: 63,
    defense: 80,
  },
  {
    id: 9,
    name: 'Blastoise',
    type: ['Water'],
    health: 79,
    attack: 83,
    defense: 100,
  },
  {
    id: 10,
    name: 'Caterpie',
    type: ['Bug'],
    health: 45,
    attack: 30,
    defense: 35,
  },
  {
    id: 11,
    name: 'Metapod',
    type: ['Bug'],
    health: 50,
    attack: 20,
    defense: 55,
  },
  {
    id: 12,
    name: 'Butterfree',
    type: ['Bug', 'Flying'],
    health: 60,
    attack: 45,
    defense: 50,
  },
  {
    id: 13,
    name: 'Weedle',
    type: ['Bug', 'Poison'],
    health: 40,
    attack: 35,
    defense: 30,
  },
  {
    id: 14,
    name: 'Kakuna',
    type: ['Bug', 'Poison'],
    health: 45,
    attack: 25,
    defense: 50,
  },
  {
    id: 15,
    name: 'Beedrill',
    type: ['Bug', 'Poison'],
    health: 65,
    attack: 90,
    defense: 40,
  },
  {
    id: 16,
    name: 'Pidgey',
    type: ['Normal', 'Flying'],
    health: 40,
    attack: 45,
    defense: 40,
  },
  {
    id: 17,
    name: 'Pidgeotto',
    type: ['Normal', 'Flying'],
    health: 63,
    attack: 60,
    defense: 55,
  },
  {
    id: 18,
    name: 'Pidgeot',
    type: ['Normal', 'Flying'],
    health: 83,
    attack: 80,
    defense: 75,
  },
  {
    id: 19,
    name: 'Rattata',
    type: ['Normal'],
    health: 30,
    attack: 56,
    defense: 35,
  },
  {
    id: 20,
    name: 'Raticate',
    type: ['Normal'],
    health: 55,
    attack: 81,
    defense: 60,
  },
  {
    id: 21,
    name: 'Spearow',
    type: ['Normal', 'Flying'],
    health: 40,
    attack: 60,
    defense: 30,
  },
  {
    id: 22,
    name: 'Fearow',
    type: ['Normal', 'Flying'],
    health: 65,
    attack: 90,
    defense: 65,
  },
  {
    id: 23,
    name: 'Ekans',
    type: ['Poison'],
    health: 35,
    attack: 60,
    defense: 44,
  },
  {
    id: 24,
    name: 'Arbok',
    type: ['Poison'],
    health: 60,
    attack: 95,
    defense: 69,
  },
  {
    id: 25,
    name: 'Pikachu',
    type: ['Electric'],
    health: 35,
    attack: 55,
    defense: 40,
  },
  {
    id: 26,
    name: 'Raichu',
    type: ['Electric'],
    health: 60,
    attack: 90,
    defense: 55,
  },
  {
    id: 27,
    name: 'Sandshrew',
    type: ['Ground'],
    health: 50,
    attack: 75,
    defense: 85,
  },
  {
    id: 28,
    name: 'Sandslash',
    type: ['Ground'],
    health: 75,
    attack: 100,
    defense: 110,
  },
  {
    id: 29,
    name: 'Nidoran♀',
    type: ['Poison'],
    health: 55,
    attack: 47,
    defense: 52,
  },
  {
    id: 30,
    name: 'Nidorina',
    type: ['Poison'],
    health: 70,
    attack: 62,
    defense: 67,
  },
  {
    id: 31,
    name: 'Nidoqueen',
    type: ['Poison', 'Ground'],
    health: 90,
    attack: 92,
    defense: 87,
  },
  {
    id: 32,
    name: 'Nidoran♂',
    type: ['Poison'],
    health: 46,
    attack: 57,
    defense: 40,
  },
  {
    id: 33,
    name: 'Nidorino',
    type: ['Poison'],
    health: 61,
    attack: 72,
    defense: 57,
  },
  {
    id: 34,
    name: 'Nidoking',
    type: ['Poison', 'Ground'],
    health: 81,
    attack: 102,
    defense: 77,
  },
  {
    id: 35,
    name: 'Clefairy',
    type: ['Fairy'],
    health: 70,
    attack: 45,
    defense: 48,
  },
  {
    id: 36,
    name: 'Clefable',
    type: ['Fairy'],
    health: 95,
    attack: 70,
    defense: 73,
  },
  {
    id: 37,
    name: 'Vulpix',
    type: ['Fire'],
    health: 38,
    attack: 41,
    defense: 40,
  },
  {
    id: 38,
    name: 'Ninetales',
    type: ['Fire'],
    health: 73,
    attack: 76,
    defense: 75,
  },
  {
    id: 39,
    name: 'Jigglypuff',
    type: ['Normal', 'Fairy'],
    health: 115,
    attack: 45,
    defense: 20,
  },
  {
    id: 40,
    name: 'Wigglytuff',
    type: ['Normal', 'Fairy'],
    health: 140,
    attack: 70,
    defense: 45,
  },
  {
    id: 41,
    name: 'Zubat',
    type: ['Poison', 'Flying'],
    health: 40,
    attack: 45,
    defense: 35,
  },
  {
    id: 42,
    name: 'Golbat',
    type: ['Poison', 'Flying'],
    health: 75,
    attack: 80,
    defense: 70,
  },
  {
    id: 43,
    name: 'Oddish',
    type: ['Grass', 'Poison'],
    health: 45,
    attack: 50,
    defense: 55,
  },
  {
    id: 44,
    name: 'Gloom',
    type: ['Grass', 'Poison'],
    health: 60,
    attack: 65,
    defense: 70,
  },
  {
    id: 45,
    name: 'Vileplume',
    type: ['Grass', 'Poison'],
    health: 75,
    attack: 80,
    defense: 85,
  },
  {
    id: 46,
    name: 'Paras',
    type: ['Bug', 'Grass'],
    health: 35,
    attack: 70,
    defense: 55,
  },
  {
    id: 47,
    name: 'Parasect',
    type: ['Bug', 'Grass'],
    health: 60,
    attack: 95,
    defense: 80,
  },
  {
    id: 48,
    name: 'Venonat',
    type: ['Bug', 'Poison'],
    health: 60,
    attack: 55,
    defense: 50,
  },
  {
    id: 49,
    name: 'Venomoth',
    type: ['Bug', 'Poison'],
    health: 70,
    attack: 65,
    defense: 60,
  },
  {
    id: 50,
    name: 'Diglett',
    type: ['Ground'],
    health: 10,
    attack: 55,
    defense: 25,
  },
  {
    id: 51,
    name: 'Dugtrio',
    type: ['Ground'],
    health: 35,
    attack: 100,
    defense: 50,
  },
  {
    id: 52,
    name: 'Meowth',
    type: ['Normal'],
    health: 40,
    attack: 45,
    defense: 35,
  },
  {
    id: 53,
    name: 'Persian',
    type: ['Normal'],
    health: 65,
    attack: 70,
    defense: 60,
  },
  {
    id: 54,
    name: 'Psyduck',
    type: ['Water'],
    health: 50,
    attack: 52,
    defense: 48,
  },
  {
    id: 55,
    name: 'Golduck',
    type: ['Water'],
    health: 80,
    attack: 82,
    defense: 78,
  },
  {
    id: 56,
    name: 'Mankey',
    type: ['Fighting'],
    health: 40,
    attack: 80,
    defense: 35,
  },
  {
    id: 57,
    name: 'Primeape',
    type: ['Fighting'],
    health: 65,
    attack: 105,
    defense: 60,
  },
  {
    id: 58,
    name: 'Growlithe',
    type: ['Fire'],
    health: 55,
    attack: 70,
    defense: 45,
  },
  {
    id: 59,
    name: 'Arcanine',
    type: ['Fire'],
    health: 90,
    attack: 110,
    defense: 80,
  },
  {
    id: 60,
    name: 'Poliwag',
    type: ['Water'],
    health: 40,
    attack: 50,
    defense: 40,
  },
  {
    id: 61,
    name: 'Poliwhirl',
    type: ['Water'],
    health: 65,
    attack: 65,
    defense: 65,
  },
  {
    id: 62,
    name: 'Poliwrath',
    type: ['Water', 'Fighting'],
    health: 90,
    attack: 95,
    defense: 95,
  },
  {
    id: 63,
    name: 'Abra',
    type: ['Psychic'],
    health: 25,
    attack: 20,
    defense: 15,
  },
  {
    id: 64,
    name: 'Kadabra',
    type: ['Psychic'],
    health: 40,
    attack: 35,
    defense: 30,
  },
  {
    id: 65,
    name: 'Alakazam',
    type: ['Psychic'],
    health: 55,
    attack: 50,
    defense: 45,
  },
  {
    id: 66,
    name: 'Machop',
    type: ['Fighting'],
    health: 70,
    attack: 80,
    defense: 50,
  },
  {
    id: 67,
    name: 'Machoke',
    type: ['Fighting'],
    health: 80,
    attack: 100,
    defense: 70,
  },
  {
    id: 68,
    name: 'Machamp',
    type: ['Fighting'],
    health: 90,
    attack: 130,
    defense: 80,
  },
  {
    id: 69,
    name: 'Bellsprout',
    type: ['Grass', 'Poison'],
    health: 50,
    attack: 75,
    defense: 35,
  },
  {
    id: 70,
    name: 'Weepinbell',
    type: ['Grass', 'Poison'],
    health: 65,
    attack: 90,
    defense: 50,
  },
  {
    id: 71,
    name: 'Victreebel',
    type: ['Grass', 'Poison'],
    health: 80,
    attack: 105,
    defense: 65,
  },
  {
    id: 72,
    name: 'Tentacool',
    type: ['Water', 'Poison'],
    health: 40,
    attack: 40,
    defense: 35,
  },
  {
    id: 73,
    name: 'Tentacruel',
    type: ['Water', 'Poison'],
    health: 80,
    attack: 70,
    defense: 65,
  },
  {
    id: 74,
    name: 'Geodude',
    type: ['Rock', 'Ground'],
    health: 40,
    attack: 80,
    defense: 100,
  },
  {
    id: 75,
    name: 'Graveler',
    type: ['Rock', 'Ground'],
    health: 55,
    attack: 95,
    defense: 115,
  },
  {
    id: 76,
    name: 'Golem',
    type: ['Rock', 'Ground'],
    health: 80,
    attack: 120,
    defense: 130,
  },
  {
    id: 77,
    name: 'Ponyta',
    type: ['Fire'],
    health: 50,
    attack: 85,
    defense: 55,
  },
  {
    id: 78,
    name: 'Rapidash',
    type: ['Fire'],
    health: 65,
    attack: 100,
    defense: 70,
  },
  {
    id: 79,
    name: 'Slowpoke',
    type: ['Water', 'Psychic'],
    health: 90,
    attack: 65,
    defense: 65,
  },
  {
    id: 80,
    name: 'Slowbro',
    type: ['Water', 'Psychic'],
    health: 95,
    attack: 75,
    defense: 110,
  },
  {
    id: 81,
    name: 'Magnemite',
    type: ['Electric', 'Steel'],
    health: 25,
    attack: 35,
    defense: 70,
  },
  {
    id: 82,
    name: 'Magneton',
    type: ['Electric', 'Steel'],
    health: 50,
    attack: 60,
    defense: 95,
  },
  {
    id: 83,
    name: "Farfetch'd",
    type: ['Normal', 'Flying'],
    health: 52,
    attack: 90,
    defense: 55,
  },
  {
    id: 84,
    name: 'Doduo',
    type: ['Normal', 'Flying'],
    health: 35,
    attack: 85,
    defense: 45,
  },
  {
    id: 85,
    name: 'Dodrio',
    type: ['Normal', 'Flying'],
    health: 60,
    attack: 110,
    defense: 70,
  },
  {
    id: 86,
    name: 'Seel',
    type: ['Water'],
    health: 65,
    attack: 45,
    defense: 55,
  },
  {
    id: 87,
    name: 'Dewgong',
    type: ['Water', 'Ice'],
    health: 90,
    attack: 70,
    defense: 80,
  },
  {
    id: 88,
    name: 'Grimer',
    type: ['Poison'],
    health: 80,
    attack: 80,
    defense: 50,
  },
  {
    id: 89,
    name: 'Muk',
    type: ['Poison'],
    health: 105,
    attack: 105,
    defense: 75,
  },
  {
    id: 90,
    name: 'Shellder',
    type: ['Water'],
    health: 30,
    attack: 65,
    defense: 100,
  },
  {
    id: 91,
    name: 'Cloyster',
    type: ['Water', 'Ice'],
    health: 50,
    attack: 95,
    defense: 180,
  },
  {
    id: 92,
    name: 'Gastly',
    type: ['Ghost', 'Poison'],
    health: 30,
    attack: 35,
    defense: 30,
  },
  {
    id: 93,
    name: 'Haunter',
    type: ['Ghost', 'Poison'],
    health: 45,
    attack: 50,
    defense: 45,
  },
  {
    id: 94,
    name: 'Gengar',
    type: ['Ghost', 'Poison'],
    health: 60,
    attack: 65,
    defense: 60,
  },
  {
    id: 95,
    name: 'Onix',
    type: ['Rock', 'Ground'],
    health: 35,
    attack: 45,
    defense: 160,
  },
  {
    id: 96,
    name: 'Drowzee',
    type: ['Psychic'],
    health: 60,
    attack: 48,
    defense: 45,
  },
  {
    id: 97,
    name: 'Hypno',
    type: ['Psychic'],
    health: 85,
    attack: 73,
    defense: 70,
  },
  {
    id: 98,
    name: 'Krabby',
    type: ['Water'],
    health: 30,
    attack: 105,
    defense: 90,
  },
  {
    id: 99,
    name: 'Kingler',
    type: ['Water'],
    health: 55,
    attack: 130,
    defense: 115,
  },
  {
    id: 100,
    name: 'Voltorb',
    type: ['Electric'],
    health: 40,
    attack: 30,
    defense: 50,
  },
  {
    id: 101,
    name: 'Electrode',
    type: ['Electric'],
    health: 60,
    attack: 50,
    defense: 70,
  },
  {
    id: 102,
    name: 'Exeggcute',
    type: ['Grass', 'Psychic'],
    health: 60,
    attack: 40,
    defense: 80,
  },
  {
    id: 103,
    name: 'Exeggutor',
    type: ['Grass', 'Psychic'],
    health: 95,
    attack: 95,
    defense: 85,
  },
  {
    id: 104,
    name: 'Cubone',
    type: ['Ground'],
    health: 50,
    attack: 50,
    defense: 95,
  },
  {
    id: 105,
    name: 'Marowak',
    type: ['Ground'],
    health: 60,
    attack: 80,
    defense: 110,
  },
  {
    id: 106,
    name: 'Hitmonlee',
    type: ['Fighting'],
    health: 50,
    attack: 120,
    defense: 53,
  },
  {
    id: 107,
    name: 'Hitmonchan',
    type: ['Fighting'],
    health: 50,
    attack: 105,
    defense: 79,
  },
  {
    id: 108,
    name: 'Lickitung',
    type: ['Normal'],
    health: 90,
    attack: 55,
    defense: 75,
  },
  {
    id: 109,
    name: 'Koffing',
    type: ['Poison'],
    health: 40,
    attack: 65,
    defense: 95,
  },
  {
    id: 110,
    name: 'Weezing',
    type: ['Poison'],
    health: 65,
    attack: 90,
    defense: 120,
  },
  {
    id: 111,
    name: 'Rhyhorn',
    type: ['Ground', 'Rock'],
    health: 80,
    attack: 85,
    defense: 95,
  },
  {
    id: 112,
    name: 'Rhydon',
    type: ['Ground', 'Rock'],
    health: 105,
    attack: 130,
    defense: 120,
  },
  {
    id: 113,
    name: 'Chansey',
    type: ['Normal'],
    health: 250,
    attack: 5,
    defense: 5,
  },
  {
    id: 114,
    name: 'Tangela',
    type: ['Grass'],
    health: 65,
    attack: 55,
    defense: 115,
  },
  {
    id: 115,
    name: 'Kangaskhan',
    type: ['Normal'],
    health: 105,
    attack: 95,
    defense: 80,
  },
  {
    id: 116,
    name: 'Horsea',
    type: ['Water'],
    health: 30,
    attack: 40,
    defense: 70,
  },
  {
    id: 117,
    name: 'Seadra',
    type: ['Water'],
    health: 55,
    attack: 65,
    defense: 95,
  },
  {
    id: 118,
    name: 'Goldeen',
    type: ['Water'],
    health: 45,
    attack: 67,
    defense: 60,
  },
  {
    id: 119,
    name: 'Seaking',
    type: ['Water'],
    health: 80,
    attack: 92,
    defense: 65,
  },
  {
    id: 120,
    name: 'Staryu',
    type: ['Water'],
    health: 30,
    attack: 45,
    defense: 55,
  },
  {
    id: 121,
    name: 'Starmie',
    type: ['Water', 'Psychic'],
    health: 60,
    attack: 75,
    defense: 85,
  },
  {
    id: 122,
    name: 'Mr. Mime',
    type: ['Psychic', 'Fairy'],
    health: 40,
    attack: 45,
    defense: 65,
  },
  {
    id: 123,
    name: 'Scyther',
    type: ['Bug', 'Flying'],
    health: 70,
    attack: 110,
    defense: 80,
  },
  {
    id: 124,
    name: 'Jynx',
    type: ['Ice', 'Psychic'],
    health: 65,
    attack: 50,
    defense: 35,
  },
  {
    id: 125,
    name: 'Electabuzz',
    type: ['Electric'],
    health: 65,
    attack: 83,
    defense: 57,
  },
  {
    id: 126,
    name: 'Magmar',
    type: ['Fire'],
    health: 65,
    attack: 95,
    defense: 57,
  },
  {
    id: 127,
    name: 'Pinsir',
    type: ['Bug'],
    health: 65,
    attack: 125,
    defense: 100,
  },
  {
    id: 128,
    name: 'Tauros',
    type: ['Normal'],
    health: 75,
    attack: 100,
    defense: 95,
  },
  {
    id: 129,
    name: 'Magikarp',
    type: ['Water'],
    health: 20,
    attack: 10,
    defense: 55,
  },
  {
    id: 130,
    name: 'Gyarados',
    type: ['Water', 'Flying'],
    health: 95,
    attack: 125,
    defense: 79,
  },
  {
    id: 131,
    name: 'Lapras',
    type: ['Water', 'Ice'],
    health: 130,
    attack: 85,
    defense: 80,
  },
  {
    id: 132,
    name: 'Ditto',
    type: ['Normal'],
    health: 48,
    attack: 48,
    defense: 48,
  },
  {
    id: 133,
    name: 'Eevee',
    type: ['Normal'],
    health: 55,
    attack: 55,
    defense: 50,
  },
  {
    id: 134,
    name: 'Vaporeon',
    type: ['Water'],
    health: 130,
    attack: 65,
    defense: 60,
  },
  {
    id: 135,
    name: 'Jolteon',
    type: ['Electric'],
    health: 65,
    attack: 65,
    defense: 60,
  },
  {
    id: 136,
    name: 'Flareon',
    type: ['Fire'],
    health: 65,
    attack: 130,
    defense: 60,
  },
  {
    id: 137,
    name: 'Porygon',
    type: ['Normal'],
    health: 65,
    attack: 60,
    defense: 70,
  },
  {
    id: 138,
    name: 'Omanyte',
    type: ['Rock', 'Water'],
    health: 35,
    attack: 40,
    defense: 100,
  },
  {
    id: 139,
    name: 'Omastar',
    type: ['Rock', 'Water'],
    health: 70,
    attack: 60,
    defense: 125,
  },
  {
    id: 140,
    name: 'Kabuto',
    type: ['Rock', 'Water'],
    health: 30,
    attack: 80,
    defense: 90,
  },
  {
    id: 141,
    name: 'Kabutops',
    type: ['Rock', 'Water'],
    health: 60,
    attack: 115,
    defense: 105,
  },
  {
    id: 142,
    name: 'Aerodactyl',
    type: ['Rock', 'Flying'],
    health: 80,
    attack: 105,
    defense: 65,
  },
  {
    id: 143,
    name: 'Snorlax',
    type: ['Normal'],
    health: 160,
    attack: 110,
    defense: 65,
  },
  {
    id: 144,
    name: 'Articuno',
    type: ['Ice', 'Flying'],
    health: 90,
    attack: 85,
    defense: 100,
  },
  {
    id: 145,
    name: 'Zapdos',
    type: ['Electric', 'Flying'],
    health: 90,
    attack: 90,
    defense: 85,
  },
  {
    id: 146,
    name: 'Moltres',
    type: ['Fire', 'Flying'],
    health: 90,
    attack: 100,
    defense: 90,
  },
  {
    id: 147,
    name: 'Dratini',
    type: ['Dragon'],
    health: 41,
    attack: 64,
    defense: 45,
  },
  {
    id: 148,
    name: 'Dragonair',
    type: ['Dragon'],
    health: 61,
    attack: 84,
    defense: 65,
  },
  {
    id: 149,
    name: 'Dragonite',
    type: ['Dragon', 'Flying'],
    health: 91,
    attack: 134,
    defense: 95,
  },
  {
    id: 150,
    name: 'Mewtwo',
    type: ['Psychic'],
    health: 106,
    attack: 110,
    defense: 90,
  },
  {
    id: 151,
    name: 'Mew',
    type: ['Psychic'],
    health: 100,
    attack: 100,
    defense: 100,
  },
];
