packages:
  - 'design-system/docs'
  - 'design-system/docs/storybook'
  - 'design-system/pkg'
  - 'design-system/primitives'
  - 'dev-projects/*'
  - 'docs'
  - 'keystatic'
  - 'packages/*'
  - 'templates/*'

allowBuilds:
  '@swc/core': true
  core-js-pure: false
  esbuild: true
  sharp: true
  workerd: true

catalog:
  react-aria: 3.50.0
  react-stately: 3.48.0

minimumReleaseAgeExclude:
  - '@preconstruct/cli@2.9.0'

# Ensure environment variables defined via NPM scripts work consistently for all operating systems.
shellEmulator: true
