packages:
  - 'design-system/docs'
  - 'design-system/docs/storybook'
  - 'design-system/pkg'
  - 'design-system/primitives'
  - 'dev-projects/*'
  - 'docs'
  - 'keystatic'
  - 'packages/*'
  - 'templates/*'

allowBuilds:
  '@swc/core': true
  core-js-pure: false
  esbuild: true
  sharp: true
  workerd: true

catalog:
  react-aria: 3.51.0
  react-stately: 3.49.0
  react-aria-components: 1.20.0

# Ensure environment variables defined via NPM scripts work consistently for all operating systems.
shellEmulator: true
