/**
 * Do not edit directly
 * Generated on Fri, 03 Nov 2023 05:52:12 GMT
 */

export const tokenSchema = {
  animation: {
    duration: {
      short: 'var(--kui-animation-duration-short)',
      regular: 'var(--kui-animation-duration-regular)',
      long: 'var(--kui-animation-duration-long)',
      xlong: 'var(--kui-animation-duration-xlong)',
    },
    easing: {
      easeInOut: 'var(--kui-animation-easing-ease-in-out)',
      easeIn: 'var(--kui-animation-easing-ease-in)',
      easeOut: 'var(--kui-animation-easing-ease-out)',
    },
  },
  size: {
    alias: {
      focusRing: 'var(--kui-size-alias-focus-ring)',
      focusRingGap: 'var(--kui-size-alias-focus-ring-gap)',
      singleLineHeight: 'var(--kui-size-alias-single-line-height)',
      singleLineWidth: 'var(--kui-size-alias-single-line-width)',
    },
    element: {
      xsmall: 'var(--kui-size-element-xsmall)',
      small: 'var(--kui-size-element-small)',
      regular: 'var(--kui-size-element-regular)',
      medium: 'var(--kui-size-element-medium)',
      large: 'var(--kui-size-element-large)',
      xlarge: 'var(--kui-size-element-xlarge)',
    },
    icon: {
      small: 'var(--kui-size-icon-small)',
      regular: 'var(--kui-size-icon-regular)',
      medium: 'var(--kui-size-icon-medium)',
      large: 'var(--kui-size-icon-large)',
    },
    container: {
      xsmall: 'var(--kui-size-container-xsmall)',
      small: 'var(--kui-size-container-small)',
      medium: 'var(--kui-size-container-medium)',
      large: 'var(--kui-size-container-large)',
      xlarge: 'var(--kui-size-container-xlarge)',
    },
    dialog: {
      xsmall: 'var(--kui-size-dialog-xsmall)',
      small: 'var(--kui-size-dialog-small)',
      medium: 'var(--kui-size-dialog-medium)',
      large: 'var(--kui-size-dialog-large)',
    },
    border: {
      regular: 'var(--kui-size-border-regular)',
      medium: 'var(--kui-size-border-medium)',
      large: 'var(--kui-size-border-large)',
    },
    radius: {
      full: 'var(--kui-size-radius-full)',
      xsmall: 'var(--kui-size-radius-xsmall)',
      small: 'var(--kui-size-radius-small)',
      regular: 'var(--kui-size-radius-regular)',
      medium: 'var(--kui-size-radius-medium)',
      large: 'var(--kui-size-radius-large)',
      xlarge: 'var(--kui-size-radius-xlarge)',
    },
    shadow: {
      small: 'var(--kui-size-shadow-small)',
      medium: 'var(--kui-size-shadow-medium)',
      large: 'var(--kui-size-shadow-large)',
    },
    space: {
      xsmall: 'var(--kui-size-space-xsmall)',
      small: 'var(--kui-size-space-small)',
      regular: 'var(--kui-size-space-regular)',
      medium: 'var(--kui-size-space-medium)',
      large: 'var(--kui-size-space-large)',
      xlarge: 'var(--kui-size-space-xlarge)',
      xxlarge: 'var(--kui-size-space-xxlarge)',
    },
    scale: {
      '0': 'var(--kui-size-scale-0)',
      '10': 'var(--kui-size-scale-10)',
      '25': 'var(--kui-size-scale-25)',
      '40': 'var(--kui-size-scale-40)',
      '50': 'var(--kui-size-scale-50)',
      '65': 'var(--kui-size-scale-65)',
      '75': 'var(--kui-size-scale-75)',
      '85': 'var(--kui-size-scale-85)',
      '100': 'var(--kui-size-scale-100)',
      '115': 'var(--kui-size-scale-115)',
      '125': 'var(--kui-size-scale-125)',
      '130': 'var(--kui-size-scale-130)',
      '150': 'var(--kui-size-scale-150)',
      '160': 'var(--kui-size-scale-160)',
      '175': 'var(--kui-size-scale-175)',
      '200': 'var(--kui-size-scale-200)',
      '225': 'var(--kui-size-scale-225)',
      '250': 'var(--kui-size-scale-250)',
      '275': 'var(--kui-size-scale-275)',
      '300': 'var(--kui-size-scale-300)',
      '325': 'var(--kui-size-scale-325)',
      '350': 'var(--kui-size-scale-350)',
      '400': 'var(--kui-size-scale-400)',
      '450': 'var(--kui-size-scale-450)',
      '500': 'var(--kui-size-scale-500)',
      '550': 'var(--kui-size-scale-550)',
      '600': 'var(--kui-size-scale-600)',
      '675': 'var(--kui-size-scale-675)',
      '700': 'var(--kui-size-scale-700)',
      '800': 'var(--kui-size-scale-800)',
      '900': 'var(--kui-size-scale-900)',
      '1000': 'var(--kui-size-scale-1000)',
      '1200': 'var(--kui-size-scale-1200)',
      '1250': 'var(--kui-size-scale-1250)',
      '1600': 'var(--kui-size-scale-1600)',
      '1700': 'var(--kui-size-scale-1700)',
      '2000': 'var(--kui-size-scale-2000)',
      '2400': 'var(--kui-size-scale-2400)',
      '3000': 'var(--kui-size-scale-3000)',
      '3400': 'var(--kui-size-scale-3400)',
      '3600': 'var(--kui-size-scale-3600)',
      '4600': 'var(--kui-size-scale-4600)',
      '5000': 'var(--kui-size-scale-5000)',
      '6000': 'var(--kui-size-scale-6000)',
    },
  },
  typography: {
    fontFamily: {
      base: 'var(--kui-typography-font-family-base)',
      code: 'var(--kui-typography-font-family-code)',
    },
    fontWeight: {
      regular: 'var(--kui-typography-font-weight-regular)',
      medium: 'var(--kui-typography-font-weight-medium)',
      semibold: 'var(--kui-typography-font-weight-semibold)',
      bold: 'var(--kui-typography-font-weight-bold)',
    },
    lineheight: {
      large: 'var(--kui-typography-lineheight-large)',
      medium: 'var(--kui-typography-lineheight-medium)',
      small: 'var(--kui-typography-lineheight-small)',
    },
    text: {
      small: {
        size: 'var(--kui-typography-text-small-size)',
        lineheight: 'var(--kui-typography-text-small-lineheight)',
        baselineTrim: 'var(--kui-typography-text-small-baseline-trim)',
        capheightTrim: 'var(--kui-typography-text-small-capheight-trim)',
        capheight: 'var(--kui-typography-text-small-capheight)',
      },
      regular: {
        size: 'var(--kui-typography-text-regular-size)',
        lineheight: 'var(--kui-typography-text-regular-lineheight)',
        baselineTrim: 'var(--kui-typography-text-regular-baseline-trim)',
        capheightTrim: 'var(--kui-typography-text-regular-capheight-trim)',
        capheight: 'var(--kui-typography-text-regular-capheight)',
      },
      medium: {
        size: 'var(--kui-typography-text-medium-size)',
        lineheight: 'var(--kui-typography-text-medium-lineheight)',
        baselineTrim: 'var(--kui-typography-text-medium-baseline-trim)',
        capheightTrim: 'var(--kui-typography-text-medium-capheight-trim)',
        capheight: 'var(--kui-typography-text-medium-capheight)',
      },
      large: {
        size: 'var(--kui-typography-text-large-size)',
        lineheight: 'var(--kui-typography-text-large-lineheight)',
        baselineTrim: 'var(--kui-typography-text-large-baseline-trim)',
        capheightTrim: 'var(--kui-typography-text-large-capheight-trim)',
        capheight: 'var(--kui-typography-text-large-capheight)',
      },
    },
    heading: {
      small: {
        size: 'var(--kui-typography-heading-small-size)',
        lineheight: 'var(--kui-typography-heading-small-lineheight)',
        baselineTrim: 'var(--kui-typography-heading-small-baseline-trim)',
        capheightTrim: 'var(--kui-typography-heading-small-capheight-trim)',
        capheight: 'var(--kui-typography-heading-small-capheight)',
      },
      regular: {
        size: 'var(--kui-typography-heading-regular-size)',
        lineheight: 'var(--kui-typography-heading-regular-lineheight)',
        baselineTrim: 'var(--kui-typography-heading-regular-baseline-trim)',
        capheightTrim: 'var(--kui-typography-heading-regular-capheight-trim)',
        capheight: 'var(--kui-typography-heading-regular-capheight)',
      },
      medium: {
        size: 'var(--kui-typography-heading-medium-size)',
        lineheight: 'var(--kui-typography-heading-medium-lineheight)',
        baselineTrim: 'var(--kui-typography-heading-medium-baseline-trim)',
        capheightTrim: 'var(--kui-typography-heading-medium-capheight-trim)',
        capheight: 'var(--kui-typography-heading-medium-capheight)',
      },
      large: {
        size: 'var(--kui-typography-heading-large-size)',
        lineheight: 'var(--kui-typography-heading-large-lineheight)',
        baselineTrim: 'var(--kui-typography-heading-large-baseline-trim)',
        capheightTrim: 'var(--kui-typography-heading-large-capheight-trim)',
        capheight: 'var(--kui-typography-heading-large-capheight)',
      },
    },
  },
  color: {
    alias: {
      blanket: 'var(--kui-color-alias-blanket)',
      backgroundIdle: 'var(--kui-color-alias-background-idle)',
      backgroundDisabled: 'var(--kui-color-alias-background-disabled)',
      backgroundHovered: 'var(--kui-color-alias-background-hovered)',
      backgroundFocused: 'var(--kui-color-alias-background-focused)',
      backgroundPressed: 'var(--kui-color-alias-background-pressed)',
      backgroundSelected: 'var(--kui-color-alias-background-selected)',
      backgroundSelectedHovered:
        'var(--kui-color-alias-background-selected-hovered)',
      focusRing: 'var(--kui-color-alias-focus-ring)',
      borderIdle: 'var(--kui-color-alias-border-idle)',
      borderHovered: 'var(--kui-color-alias-border-hovered)',
      borderPressed: 'var(--kui-color-alias-border-pressed)',
      borderFocused: 'var(--kui-color-alias-border-focused)',
      borderDisabled: 'var(--kui-color-alias-border-disabled)',
      borderSelected: 'var(--kui-color-alias-border-selected)',
      borderInvalid: 'var(--kui-color-alias-border-invalid)',
      foregroundIdle: 'var(--kui-color-alias-foreground-idle)',
      foregroundHovered: 'var(--kui-color-alias-foreground-hovered)',
      foregroundPressed: 'var(--kui-color-alias-foreground-pressed)',
      foregroundFocused: 'var(--kui-color-alias-foreground-focused)',
      foregroundDisabled: 'var(--kui-color-alias-foreground-disabled)',
      foregroundSelected: 'var(--kui-color-alias-foreground-selected)',
    },
    background: {
      canvas: 'var(--kui-color-background-canvas)',
      surface: 'var(--kui-color-background-surface)',
      surfaceSecondary: 'var(--kui-color-background-surface-secondary)',
      surfaceTertiary: 'var(--kui-color-background-surface-tertiary)',
      inverse: 'var(--kui-color-background-inverse)',
      accent: 'var(--kui-color-background-accent)',
      accentEmphasis: 'var(--kui-color-background-accent-emphasis)',
      positive: 'var(--kui-color-background-positive)',
      positiveEmphasis: 'var(--kui-color-background-positive-emphasis)',
      caution: 'var(--kui-color-background-caution)',
      cautionEmphasis: 'var(--kui-color-background-caution-emphasis)',
      critical: 'var(--kui-color-background-critical)',
      criticalEmphasis: 'var(--kui-color-background-critical-emphasis)',
      pending: 'var(--kui-color-background-pending)',
      pendingEmphasis: 'var(--kui-color-background-pending-emphasis)',
      highlight: 'var(--kui-color-background-highlight)',
      highlightEmphasis: 'var(--kui-color-background-highlight-emphasis)',
    },
    border: {
      muted: 'var(--kui-color-border-muted)',
      neutral: 'var(--kui-color-border-neutral)',
      emphasis: 'var(--kui-color-border-emphasis)',
      accent: 'var(--kui-color-border-accent)',
      positive: 'var(--kui-color-border-positive)',
      caution: 'var(--kui-color-border-caution)',
      critical: 'var(--kui-color-border-critical)',
      pending: 'var(--kui-color-border-pending)',
      highlight: 'var(--kui-color-border-highlight)',
    },
    foreground: {
      neutral: 'var(--kui-color-foreground-neutral)',
      neutralEmphasis: 'var(--kui-color-foreground-neutral-emphasis)',
      neutralSecondary: 'var(--kui-color-foreground-neutral-secondary)',
      neutralTertiary: 'var(--kui-color-foreground-neutral-tertiary)',
      onEmphasis: 'var(--kui-color-foreground-on-emphasis)',
      inverse: 'var(--kui-color-foreground-inverse)',
      inverseSecondary: 'var(--kui-color-foreground-inverse-secondary)',
      accent: 'var(--kui-color-foreground-accent)',
      positive: 'var(--kui-color-foreground-positive)',
      caution: 'var(--kui-color-foreground-caution)',
      critical: 'var(--kui-color-foreground-critical)',
      pending: 'var(--kui-color-foreground-pending)',
      highlight: 'var(--kui-color-foreground-highlight)',
    },
    shadow: {
      muted: 'var(--kui-color-shadow-muted)',
      regular: 'var(--kui-color-shadow-regular)',
      emphasis: 'var(--kui-color-shadow-emphasis)',
    },
    scale: {
      black: 'var(--kui-color-scale-black)',
      white: 'var(--kui-color-scale-white)',
      amber1: 'var(--kui-color-scale-amber1)',
      amber2: 'var(--kui-color-scale-amber2)',
      amber3: 'var(--kui-color-scale-amber3)',
      amber4: 'var(--kui-color-scale-amber4)',
      amber5: 'var(--kui-color-scale-amber5)',
      amber6: 'var(--kui-color-scale-amber6)',
      amber7: 'var(--kui-color-scale-amber7)',
      amber8: 'var(--kui-color-scale-amber8)',
      amber9: 'var(--kui-color-scale-amber9)',
      amber10: 'var(--kui-color-scale-amber10)',
      amber11: 'var(--kui-color-scale-amber11)',
      green1: 'var(--kui-color-scale-green1)',
      green2: 'var(--kui-color-scale-green2)',
      green3: 'var(--kui-color-scale-green3)',
      green4: 'var(--kui-color-scale-green4)',
      green5: 'var(--kui-color-scale-green5)',
      green6: 'var(--kui-color-scale-green6)',
      green7: 'var(--kui-color-scale-green7)',
      green8: 'var(--kui-color-scale-green8)',
      green9: 'var(--kui-color-scale-green9)',
      green10: 'var(--kui-color-scale-green10)',
      green11: 'var(--kui-color-scale-green11)',
      indigo1: 'var(--kui-color-scale-indigo1)',
      indigo2: 'var(--kui-color-scale-indigo2)',
      indigo3: 'var(--kui-color-scale-indigo3)',
      indigo4: 'var(--kui-color-scale-indigo4)',
      indigo5: 'var(--kui-color-scale-indigo5)',
      indigo6: 'var(--kui-color-scale-indigo6)',
      indigo7: 'var(--kui-color-scale-indigo7)',
      indigo8: 'var(--kui-color-scale-indigo8)',
      indigo9: 'var(--kui-color-scale-indigo9)',
      indigo10: 'var(--kui-color-scale-indigo10)',
      indigo11: 'var(--kui-color-scale-indigo11)',
      pink1: 'var(--kui-color-scale-pink1)',
      pink2: 'var(--kui-color-scale-pink2)',
      pink3: 'var(--kui-color-scale-pink3)',
      pink4: 'var(--kui-color-scale-pink4)',
      pink5: 'var(--kui-color-scale-pink5)',
      pink6: 'var(--kui-color-scale-pink6)',
      pink7: 'var(--kui-color-scale-pink7)',
      pink8: 'var(--kui-color-scale-pink8)',
      pink9: 'var(--kui-color-scale-pink9)',
      pink10: 'var(--kui-color-scale-pink10)',
      pink11: 'var(--kui-color-scale-pink11)',
      purple1: 'var(--kui-color-scale-purple1)',
      purple2: 'var(--kui-color-scale-purple2)',
      purple3: 'var(--kui-color-scale-purple3)',
      purple4: 'var(--kui-color-scale-purple4)',
      purple5: 'var(--kui-color-scale-purple5)',
      purple6: 'var(--kui-color-scale-purple6)',
      purple7: 'var(--kui-color-scale-purple7)',
      purple8: 'var(--kui-color-scale-purple8)',
      purple9: 'var(--kui-color-scale-purple9)',
      purple10: 'var(--kui-color-scale-purple10)',
      purple11: 'var(--kui-color-scale-purple11)',
      red1: 'var(--kui-color-scale-red1)',
      red2: 'var(--kui-color-scale-red2)',
      red3: 'var(--kui-color-scale-red3)',
      red4: 'var(--kui-color-scale-red4)',
      red5: 'var(--kui-color-scale-red5)',
      red6: 'var(--kui-color-scale-red6)',
      red7: 'var(--kui-color-scale-red7)',
      red8: 'var(--kui-color-scale-red8)',
      red9: 'var(--kui-color-scale-red9)',
      red10: 'var(--kui-color-scale-red10)',
      red11: 'var(--kui-color-scale-red11)',
      slate1: 'var(--kui-color-scale-slate1)',
      slate2: 'var(--kui-color-scale-slate2)',
      slate3: 'var(--kui-color-scale-slate3)',
      slate4: 'var(--kui-color-scale-slate4)',
      slate5: 'var(--kui-color-scale-slate5)',
      slate6: 'var(--kui-color-scale-slate6)',
      slate7: 'var(--kui-color-scale-slate7)',
      slate8: 'var(--kui-color-scale-slate8)',
      slate9: 'var(--kui-color-scale-slate9)',
      slate10: 'var(--kui-color-scale-slate10)',
      slate11: 'var(--kui-color-scale-slate11)',
    },
  },
};
