name: 'Setup Dependencies'
runs:
  using: 'composite'
  steps:
    - run: npm install -g corepack@0.31.0
      shell: bash

    - run: corepack enable
      shell: bash

    - name: Setup Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Install Dependencies
      run: pnpm install
      shell: bash
