name: Version Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  versioning:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: ./.github/actions/setup-deps

      - uses: changesets/action@v1
        with:
          version: pnpm run version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
